### PR TITLE
read_csv2() locale issues

### PR DESCRIPTION
**Pull request by krlmlr**
A message is provided if the locale is updated automatically by read_csv2(); if the caller passes an explict locale, it is not updated.

### CODE REVIEW

**Comment by hadley** [comment]
I think it always needs to update - but I like the message

**Comment by krlmlr** [comment]
Now gives message only, the message shows alternatives.

**Comment by hadley** [comment]
LGTM

**Comment by krlmlr** [comment]
Thanks, rebased. I can't merge this myself.

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
