### PR TITLE
Add cheatsheet thumbnail to README

### LINKED ISSUE #800: Add data import cheat sheet thumb to README
Add thumbnail for the data import cheat sheet to the README.

### PR DESCRIPTION
**Pull request by batpigandme**
* Fixes #800

### CODE REVIEW

**Comment by batpigandme** [comment]
I certainly can - honestly, it's a random pet peeve of mine when I click on something and it goes straight to save a file, but I have absolutely nothing to suggest that that's something that generalizes beyond yours truly.

**Comment by hadley** [comment]
We should probably just copy whatever the main cheatsheet page does

**Comment by batpigandme** [comment]
They do the auto-download — I'll live. I remembered the trauma: federal websites that download PDFs that can _only_ be opened in Acrobat Reader, thus leading to unnecessary nonsense on my computer!

There, I've spoken my truth to power, and can move on and link directly!

**Comment by jimhester** [comment]
It doesn't go to save the file though, it opens the pdf in the browser, at least on chrome

**Comment by batpigandme** [comment]
Correct. Chrome is wonderful like that!

**Comment by jimhester** [comment]
it does the same in safari, note the link I suggested is rawgit.com one, not the raw link from github, which does just download the pdf like you describe

**Comment by batpigandme** [comment]
This is why people like you, and don't like the feds! 👍

**Comment by jxu** [comment]
rawgit.com is shutting down. Better to use github hosting.

**Comment by batpigandme** [comment]
@jxu,
Would you mind filing this as a new issue? That way we can track it and close it once we switch over!
Thanks

**Pull request merged**
