### PR TITLE
fix html

### PR DESCRIPTION
**Pull request by spaette**
this is a copy/paste from googlesheets4

### CODE REVIEW

**Comment by jennybc** [comment]
This is not necessarily critique but I'm wondering: are you detecting a problem with the current site? There's no problem with the naked eye for me.

**Comment by spaette** [comment]
> current site

as opened in Chromium and Firefox

likely due to `` element's extra `/` at the end

```
<img src="https://github.com/rstudio/cheatsheets/raw/main/pngs/thumbnails/data-import-cheatsheet-
thumbs.png" height="252" alt="thumbnail of tidyverse data import cheatsheet"//>
```

> copy/paste from googlesheets4

this does two things regarding the user interface

- renders cheatsheets/data-import.pdf
- eliminates the redirect occurring for the image file

a download icon accompanies the .pdf rendering whereas currently the file is downloaded to a default directory

**Comment by jennybc** [comment]
OK I'm happy to update. The extra slash is clearly a mistake that I guess some browsers cope with.

The official workflow is to edit `README.Rmd` as per:

https://github.com/tidyverse/readr/blob/b4cb4f7270252259c30fa4dbaaee32ba9ccea0f1/README.Rmd#L5

then call `devtools::build_readme()`. If you don't update the PR, I will next time I come through here.

**Comment by spaette** [comment]
likely I'll update tomorrow

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
