### PR TITLE
switch argument order in std::string()

### PR DESCRIPTION
**Pull request by MichaelChirico**
I believe the fill constructor (6) is intended here:

https://www.cplusplus.com/reference/string/string/string/

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Is this function being used at all? 🤔

**Comment by MichaelChirico** [comment]
not sure! our build tools identified the issue

**Comment by jennybc** [comment]
Is there more context for this change, i.e. what motivates it in terms of visible behaviour?

**Comment by MichaelChirico** [comment]
this was identified statically by a linter, not at runtime.

I'm not sure what the current code does but it seems clear from the doc that (into, char) works as intended. cc @hadley as original author from the blame.

**Comment by hadley** [comment]
I have no recollection of this; it's quite likely I got it wrong and the code was never used. Might be easier to just delete it.

**Comment by MichaelChirico** [comment]
@jennybc I'll follow the maintainer's lead, WDYT?

**Comment by jennybc** [comment]
If it's dead code, then, yes let's just remove it.

**Comment by MichaelChirico** [comment]
Thanks! removed the function

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
