### PR TITLE
Fix and Tests for Issue #573

### PR DESCRIPTION
**Pull request by cb4ds**
Issue #573 affected both the fixed-width and delimited files.  Tests are included for both, no exported functions were modified.

### CODE REVIEW

**Comment by jimhester** [comment]
This looks good to me, you just need to summarize the fix in NEWS, mentioning the issue / PR and your GitHub handle.

**Comment by cb4ds** [comment]
Thanks Jim - I will update the news.  In that commit should I increment the version as well to 1.0.1  and take off the .9000 ?  Was looking at the NEWS document and noticed the dev tag still on the version.

**Comment by jimhester** [comment]
No leave the version numbers as is

**Comment by cb4ds** [comment]
Ok, sounds good.  New commit with just news changes will be up shortly

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
