### PR TITLE
Add write_excel_csv2()

### PR DESCRIPTION
**Pull request by olgamie**
Create `write_excel_csv2()` to write csv with semicolon as column separator and comma as decimal separator.

This change is required to allow majority of European users easily write csv to a format that would automatically open a csv in a correct way in Excel.

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks! Unfortunately we cannot have a dplyr dependency in readr. You can get the same behavior with the following.

```r
numeric_cols <- vapply(x, is.numeric, logical(1))
x[numeric_cols] <- lapply(x[numeric_cols], format, decimal.mark = ",")
```

Can you also add a note to NEWS.md with this change and mentioning your GitHub username. Thanks!

**Comment by jimhester** [comment]
You can push additional changes to the same branch you opened this pull request from, please do not open a new pull request! I can squash the commits when I merge if needed, so don't worry about having additional commits in the pull request.

Thanks!

**Comment by olgamie** [comment]
Thanks for the review. I addressed your comments and added tests on write_excel_csv2.

**Comment by jimhester** [comment]
Great, thanks again!

**Pull request merged**
