### PR TITLE
CLion support files

### PR DESCRIPTION
**Pull request by krlmlr**
No functional changes.

### CODE REVIEW

**Comment by jimhester** [comment]
I don't feel editor specific files should be included in the repository. I feel the same way about .Rproj files, but that ship has sailed.

If you don't want these files tracked by git you can add them to [`.git/info/exclude`](http://stackoverflow.com/a/6117232/2055486) rather than adding them to the project `.gitignore`.

**Comment by krlmlr** [comment]
How would that work with `.Rbuildignore`?

**Comment by jimhester** [comment]
You can set it to be untracked [`git update-index --assume-unchanged .Rbuildignore`](http://stackoverflow.com/a/10755704/2055486), so your local changes would not be commited

**Comment by krlmlr** [comment]
Yes, but how can I include the support files for my IDE from `R CMD build`? Arguably I don't need it that often in this repo, but I wonder about the general case.

**Comment by jimhester** [comment]
You would make the changes to `.Rbuildignore` locally to exclude your CLion files, but not commit them and use the above command to tell git to assume the file is unchanged. If you do need to commit a file to `.Rbuildignore` you can use `git update-index --no-assume-unchanged` to turn tracking back on and commit the needed lines.

I have a few support files for You Complete Me for C++ completion as well that I use locally, but I do not include them in the repository or in the built package.

**Comment by krlmlr** [comment]
This is clever, I'll keep that in mind.

**Pull request closed without merging**
